name: 'Workspace Commit'
description: 'JavaScript wrapper runs `child_process.execSync("git commit ...")` on GitHub Actions'


inputs:
  author:
    description: 'Customize `user.name` that commit messages are authored by'
    required: false

  email:
    description: 'Customize `user.email` that commit messages are authored by'
    required: false

  all:
    description: 'If assigned a value then `paths` Input is not required'
    required: false

  paths:
    description: 'Required if `all` Input is undefined, list of staged files or directories to commit'
    required: false

  message:
    description: 'Multi-line commit message describing changes'
    required: true


runs:
  using: 'node12'
  main: 'index.js'


branding:
  icon: git-commit
  color: green
